### ISSUE TITLE
Oracle Pre-Debrief Plugin error

### ISSUE THREAD

**Issue by sam-man1** [oracle-samples/ofs-sample-plugins#16]
Hi Team,

we are have downloaded the pre-debrief. we are getting error that it is asking for python exe for working  . Following are the list of error :

1) node_modules\node-sass\vendor\win32-x64-120\binding.node is not a valid Win32 application.
2) npm ERR! gyp verb find Python Python is not set from command line or npm configuration
3) npm ERR! gyp verb find Python Python is not set from environment variable PYTHON

Please check the issue.

**Comment by miquelgall** [comment]
Hi sam-man1,

Have you tried to use https://learn.microsoft.com/en-us/windows/wsl/

Using NPM is sometimes more challenging, so, using WSL makes it easier to follow the steps.
